### ISSUE TITLE
Is it possible to run videos through a url? 

### ISSUE THREAD

**Issue by kellvembarbosa** [igor11191708/swiftui-loop-videoPlayer#2]
Thank you,
I believe it's not, but here's my suggestion.

**Comment by swiftuiux** [comment]
Hi I'll take it into account and add this later as part of API
Thank you

**Comment by swiftuiux** [comment]
Hi By the way added to run videos through a url
It is not released yet You can try in the main brunch
https://github.com/The-Igor/swiftui-loop-videoplayer
