### ISSUE TITLE
Incompatible with Swift Playgrounds

### ISSUE THREAD

**Issue by talaviram** [igor11191708/swiftui-loop-videoPlayer#3]
Trying to add the package into a Swift Playgrounds app (from an iPad as an example) seems to fail.
(Xcode projects seems to work fine)

**Comment by swiftuiux** [comment]
Hi I tried on Mac 
Some ideas
Ensure you have a video file named example.mp4 in your Playground’s resources folder:
	•	Right-click the Playground file in Finder and select “Show Package Contents.”
	•	Add the example.mp4 file to the Resources folder.

<img width="988" alt="Screenshot 2024-07-24 at 11 23 22" src="https://github.com/user-attachments/assets/9cb7dd71-f432-4902-95ec-5cc4a530387e">

**Comment by talaviram** [comment]
Swift Playgrounds is a different thing than Playgrounds within Xcode.

Anyway I've tried the last Playgrounds on macOS:
https://apps.apple.com/il/app/swift-playgrounds/id1496833156?mt=12

As I see no changes on your side, I guess Apple fixed something. (working with 4.5.1)
<img width="1136" alt="image" src="https://github.com/user-attachments/assets/e7ad61bf-37d4-482e-9793-13c1a6bfc8d2">

I'll reopen if I encounter this on the iPad build, but I'm pretty sure they're using the same codebase.
(unlike Xcode which is a different project...)
