### ISSUE TITLE
unable to unmute audio

### ISSUE THREAD

**Issue by andygrall** [igor11191708/swiftui-loop-videoPlayer#6]
Hello, and thanks for this project!

I'm trying to get the seamless looping of a video, which is how I landed here. (As you probably know, the native video player will loop with a fraction of a second between iterations.)

I can get the video to play, but it's muted. I haven't tried to introduce controls yet. 

Can you help?

```
struct VideoView: View {
    @State private var playbackCommand: PlaybackCommand = .unmute  // Set default to unmute
    @State private var videoSettings = VideoSettings {
        SourceName("C Major RH 70bpm")
        Ext("mp4")
        Gravity(.resizeAspect)
        Loop()
        EColor(.red)
        EFontSize(17)
    }

    var body: some View {
        ExtVideoPlayer(
            settings: $videoSettings,  // Bind settings
            command: $playbackCommand  // Bind command
        )
        .onPlayerTimeChange { newTime in
            print("Current video time: \(newTime)")
        }
        .onPlayerEventChange { events in
            print("Player event: \(events)")
        }
        .onAppear {
            playbackCommand = .unmute
        }
    }
}

```

**Comment by swiftuiux** [comment]
Can you attach your project with the video you use? Like simple example to check that here is issue with the sound.

**Comment by andygrall** [comment]
The project is 200MB in size because it includes video. I can't upload more than 25MB here. I put it on my Dropbox:

https://www.dropbox.com/scl/fo/adxf7m0n7jkqrr23edwth/ABPReF7yxtg-eTEgvW8SAu4?rlkey=cqgnhrntyfisfy2h0iizn91ug&st=llhhe29r&dl=0

**Comment by swiftuiux** [comment]
Ok I'll take a look later

**Comment by swiftuiux** [comment]
I refactored the code; try the main branch or release 1.7.4. For your app, you just need to update the package, and everything should work in terms of sound.

If you post your app on the App Store, it would be interesting to see the final version on the App Store:) I’d appreciate it if you could share the link later. 

Please let me know if everything works in terms of sound.

**Comment by andygrall** [comment]
Awesome!! It's working, and the loop is seamless. This is going to help me so much. Thank you!

Regarding the link on the App Store, I will certainly share it. But, it's going to take some time to build the rest of the videos. We want to have 20 skills done before we release the first version.

Thanks again =)
