### ISSUE TITLE
Possible to use native controls?

### ISSUE THREAD

**Issue by andygrall** [igor11191708/swiftui-loop-videoPlayer#7]
Hi Igor,

Is it possible to use the native Apple controls with the custom ExtVideoPlayer?

I was trying to model it with your controls from your example, but I can't seem to link the button actions properly. I don't need the custom controls though if I can use the native ones somehow. I've attached the ExtVideoPlayer.swift from my project wherein I tried to add the custom controls.

[ExtVideoPlayer.swift.zip](https://github.com/user-attachments/files/16945705/ExtVideoPlayer.swift.zip)

**Comment by swiftuiux** [comment]
Hi,
It’s not possible to use Apple’s controls out of the box because the package does not cover Apple’s components. it's completely alternative implementation.
	1.	You injected the controls into ExtVideoPlayer, but it requires extra modifications. For example, @Binding public var command: PlaybackCommand should be @State public var command: PlaybackCommand, and you’ll need to remove it from every initializer.
	2.	I don’t think it’s a good idea to proceed with option 1. For instance, if a bug is found later, you’ll need to fix ExtVideoPlayer yourself instead of simply updating the package like we did last time. If the controls provided in the Video6 example are sufficient in terms of functionality and design, why not remove everything else except the controls in Video6 and use it as a wrapper view with controls? You can then update the package with new features or bug fixes later. If you encounter any difficulties modifying Video6 for your needs, I can help you.

I will think about implementing an analog of Apple’s video control panel later.

**Comment by swiftuiux** [comment]
by the way if you are satisfied with Apple's controls try the example below May be it's quite suitable for your project, just replace the "your_video" to your video

 ```swift 
import SwiftUI
import AVFoundation
import AVKit
 
class VideoPlayerViewModel: ObservableObject {
    @Published var player: AVQueuePlayer
    private var looper: AVPlayerLooper?

    init() {
        let videoURL = Bundle.main.url(forResource: "your_video", withExtension: "mp4")!
        let asset = AVURLAsset(url: videoURL)
        let playerItem = AVPlayerItem(asset: asset)
        self.player = AVQueuePlayer()
        self.looper = AVPlayerLooper(player: player, templateItem: playerItem)
    }
}

struct VideoPlayerView: View {
    @StateObject private var viewModel = VideoPlayerViewModel()
    
    var body: some View {
        VStack {
            VideoPlayer(player: viewModel.player)
                .onAppear {
                    viewModel.player.play()
                }
        }
    }
}
```

**Comment by andygrall** [comment]
Wow! That does solve the problem. I wasn't able to get it to do seamless looping before, but this little bit of code has done it. 

If it wasn't obvious, I'm not a very experienced coder. Still learning. 

Thanks for your help!
