### ISSUE TITLE
Option to add cornerRadius

### ISSUE THREAD

**Issue by juanSanchezMarin** [igor11191708/swiftui-loop-videoPlayer#8]
it would be possible to add the option of adding the cornerRadius modifier

**Comment by swiftuiux** [comment]
by the way take a look on Video6.swift in the example https://github.com/igor11191708/swiftui-video-player-example
you can reach the cornerRadius effect via 
                .mask{
                    RoundedRectangle(cornerRadius: 25)
                }
            or it does not meet your needs ?
            
            
<img width="475" alt="Screenshot 2024-11-26 at 10 14 38" src="https://github.com/user-attachments/assets/f253e856-c6db-44f4-bded-6c29b8abb375">
